"""empty message

Revision ID: 86769ef53d97
Revises: f12965293526
Create Date: 2025-02-21 17:02:43.769354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86769ef53d97'
down_revision: Union[str, None] = 'f12965293526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
