"""empty message

Revision ID: e870fcf00d35
Revises: 86769ef53d97
Create Date: 2025-02-21 17:13:46.526663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e870fcf00d35'
down_revision: Union[str, None] = '86769ef53d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
